# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cfcb10095865cf9769fe5735ae43fdf2e77c8259aaef942f304efbd025aa7ce47add60a0215918286f3f4e9cdcd93b6778b944ebcb5680727244dba864131d60

test:
  secret_key_base: 8d495467cc9d09d79f30adb6d1b688ca1a563e77417aed33f0dad9974a6870752d0937505851503a58193c608c15b3fd6f669512adb4caf4fdaf2f65152cdee4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
